---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: conjur
  name: conjur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conjur
  template:
    metadata:
      labels:
        app: conjur
    spec:
      containers:
      - image: 229573445141.dkr.ecr.us-east-2.amazonaws.com/secret-retriever:0.1.1
        imagePullPolicy: Always
        name: secrets
        env:
          - name: CONJUR_APPLIANCE_URL
            value: ""
          - name: CONJUR_ACCOUNT
            value: ""
          - name: CONJUR_SECRET
            value: ""
          - name: CONJUR_AUTHN_TOKEN_FILE
            value: /run/conjur/access-token
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: server-certificate
                key: ssl-certificate
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true
      - image: cyberark/conjur-authn-k8s-client
        imagePullPolicy: Always
        name: authenticator
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_AUTHN_URL
            value: ""
          - name: CONJUR_ACCOUNT
            value: ""
          - name: CONJUR_AUTHN_LOGIN
            value: ""
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: server-certificate
                key: ssl-certificate
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
      imagePullSecrets:
        - name: dockerpullsecret
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory

